import Head from 'next/head';
import { Open_Sans } from 'next/font/google';
import { Header } from '@/modules/index/Header/Header';

const openSans = Open_Sans({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${openSans.className}`}>
        <Header />
      </main>
    </>
  );
}
